/**
 * Grocery Icon System
 *
 * Maps grocery item names to MaterialCommunityIcons via @expo/vector-icons.
 * Uses keyword matching with category fallbacks for comprehensive coverage.
 */
import type { GroceryCategory } from '@/types/grocery';

/** MaterialCommunityIcons name type (string for flexibility) */
export type GroceryIconName = string;

// ---------------------------------------------------------------------------
// Category-level fallback icons
// ---------------------------------------------------------------------------
export const CATEGORY_ICONS: Record<GroceryCategory, GroceryIconName> = {
    produce: 'fruit-cherries',
    dairy: 'cup',
    meat: 'food-drumstick',
    bakery: 'bread-slice',
    frozen: 'snowflake',
    pantry: 'cupboard-outline',
    beverages: 'cup-water',
    snacks: 'cookie',
    household: 'broom',
    personal: 'hand-wash-outline',
};

// ---------------------------------------------------------------------------
// Keyword → icon mapping
// Ordered so more specific keywords come first (e.g. "green bean" before "bean")
// ---------------------------------------------------------------------------
const ICON_MAP: [string, GroceryIconName][] = [
    // ── Produce: Fruits ──
    ['apple', 'food-apple'],
    ['banana', 'fruit-pineapple'],
    ['orange', 'fruit-citrus'],
    ['tangerine', 'fruit-citrus'],
    ['clementine', 'fruit-citrus'],
    ['mandarin', 'fruit-citrus'],
    ['grapefruit', 'fruit-citrus'],
    ['lemon', 'fruit-citrus'],
    ['lime', 'fruit-citrus'],
    ['grape', 'fruit-grapes'],
    ['strawberry', 'fruit-cherries'],
    ['blueberry', 'fruit-cherries'],
    ['raspberry', 'fruit-cherries'],
    ['blackberry', 'fruit-cherries'],
    ['cherry', 'fruit-cherries'],
    ['cranberry', 'fruit-cherries'],
    ['watermelon', 'fruit-watermelon'],
    ['melon', 'fruit-watermelon'],
    ['cantaloupe', 'fruit-watermelon'],
    ['honeydew', 'fruit-watermelon'],
    ['pineapple', 'fruit-pineapple'],
    ['mango', 'food-apple'],
    ['papaya', 'food-apple'],
    ['peach', 'food-apple'],
    ['nectarine', 'food-apple'],
    ['plum', 'food-apple'],
    ['apricot', 'food-apple'],
    ['pear', 'food-apple'],
    ['fig', 'food-apple'],
    ['pomegranate', 'food-apple'],
    ['kiwi', 'food-apple'],
    ['coconut', 'food-apple'],
    ['date', 'food-apple'],
    ['passion fruit', 'food-apple'],
    ['guava', 'food-apple'],
    ['lychee', 'food-apple'],
    ['dragon fruit', 'food-apple'],
    ['star fruit', 'food-apple'],
    ['persimmon', 'food-apple'],

    // ── Produce: Vegetables ──
    ['carrot', 'carrot'],
    ['corn', 'corn'],
    ['chili', 'chili-mild'],
    ['jalapeño', 'chili-hot'],
    ['jalapeno', 'chili-hot'],
    ['habanero', 'chili-hot'],
    ['serrano', 'chili-hot'],
    ['hot pepper', 'chili-hot'],
    ['pepper', 'chili-mild'],
    ['bell pepper', 'chili-mild'],
    ['mushroom', 'mushroom'],
    ['lettuce', 'leaf'],
    ['spinach', 'leaf'],
    ['kale', 'leaf'],
    ['arugula', 'leaf'],
    ['chard', 'leaf'],
    ['collard', 'leaf'],
    ['basil', 'leaf'],
    ['mint', 'leaf'],
    ['cilantro', 'leaf'],
    ['parsley', 'leaf'],
    ['dill', 'leaf'],
    ['rosemary', 'leaf'],
    ['thyme', 'leaf'],
    ['oregano', 'leaf'],
    ['sage', 'leaf'],
    ['herb', 'leaf'],
    ['greens', 'leaf'],
    ['mixed greens', 'leaf'],
    ['spring mix', 'leaf'],
    ['salad', 'leaf'],
    ['cabbage', 'leaf'],
    ['broccoli', 'tree'],
    ['cauliflower', 'tree'],
    ['brussels sprout', 'tree'],
    ['tomato', 'food-apple'],
    ['onion', 'circle-double'],
    ['shallot', 'circle-double'],
    ['leek', 'circle-double'],
    ['scallion', 'circle-double'],
    ['green onion', 'circle-double'],
    ['garlic', 'circle-double'],
    ['ginger', 'circle-double'],
    ['potato', 'potato'],
    ['sweet potato', 'potato'],
    ['yam', 'potato'],
    ['turnip', 'potato'],
    ['beet', 'potato'],
    ['radish', 'potato'],
    ['parsnip', 'potato'],
    ['rutabaga', 'potato'],
    ['celery', 'grass'],
    ['asparagus', 'grass'],
    ['green bean', 'grass'],
    ['snap pea', 'grass'],
    ['snow pea', 'grass'],
    ['cucumber', 'cucumber'],
    ['pickle', 'cucumber'],
    ['zucchini', 'cucumber'],
    ['squash', 'pumpkin'],
    ['pumpkin', 'pumpkin'],
    ['butternut', 'pumpkin'],
    ['acorn squash', 'pumpkin'],
    ['spaghetti squash', 'pumpkin'],
    ['eggplant', 'food-apple'],
    ['artichoke', 'flower'],
    ['avocado', 'food-apple'],
    ['edamame', 'soybean'],
    ['tofu', 'cube-outline'],
    ['tempeh', 'cube-outline'],
    ['pea', 'seed'],
    ['bean sprout', 'sprout'],
    ['sprout', 'sprout'],
    ['microgreen', 'sprout'],
    ['alfalfa', 'sprout'],

    // ── Dairy & Eggs ──
    ['whole milk', 'cup'],
    ['skim milk', 'cup'],
    ['oat milk', 'cup'],
    ['almond milk', 'cup'],
    ['soy milk', 'cup'],
    ['coconut milk', 'cup'],
    ['milk', 'cup'],
    ['half and half', 'cup'],
    ['heavy cream', 'cup'],
    ['whipping cream', 'cup'],
    ['cream', 'cup'],
    ['egg', 'egg'],
    ['eggs', 'egg'],
    ['yogurt', 'cup'],
    ['greek yogurt', 'cup'],
    ['kefir', 'cup'],
    ['cottage cheese', 'cheese'],
    ['cream cheese', 'cheese'],
    ['ricotta', 'cheese'],
    ['mascarpone', 'cheese'],
    ['parmesan', 'cheese'],
    ['parmigiano', 'cheese'],
    ['mozzarella', 'cheese'],
    ['cheddar', 'cheese'],
    ['swiss', 'cheese'],
    ['provolone', 'cheese'],
    ['gouda', 'cheese'],
    ['brie', 'cheese'],
    ['camembert', 'cheese'],
    ['feta', 'cheese'],
    ['goat cheese', 'cheese'],
    ['blue cheese', 'cheese'],
    ['gruyere', 'cheese'],
    ['havarti', 'cheese'],
    ['manchego', 'cheese'],
    ['monterey jack', 'cheese'],
    ['colby', 'cheese'],
    ['pepper jack', 'cheese'],
    ['cheese', 'cheese'],
    ['butter', 'cube'],
    ['margarine', 'cube'],
    ['ghee', 'cube'],
    ['sour cream', 'bowl-mix'],
    ['ice cream', 'ice-cream'],
    ['gelato', 'ice-cream'],
    ['sorbet', 'ice-cream'],
    ['frozen yogurt', 'ice-cream'],
    ['popsicle', 'ice-pop'],
    ['whipped cream', 'bowl-mix'],

    // ── Meat & Seafood ──
    ['chicken breast', 'food-drumstick'],
    ['chicken thigh', 'food-drumstick'],
    ['chicken wing', 'food-drumstick'],
    ['chicken tender', 'food-drumstick'],
    ['rotisserie', 'food-drumstick'],
    ['chicken', 'food-drumstick'],
    ['turkey', 'food-turkey'],
    ['duck', 'food-drumstick'],
    ['ground beef', 'food-steak'],
    ['ground turkey', 'food-steak'],
    ['ground pork', 'food-steak'],
    ['ground', 'food-steak'],
    ['steak', 'food-steak'],
    ['ribeye', 'food-steak'],
    ['sirloin', 'food-steak'],
    ['filet', 'food-steak'],
    ['beef', 'food-steak'],
    ['brisket', 'food-steak'],
    ['roast', 'food-steak'],
    ['pork chop', 'food-steak'],
    ['pork loin', 'food-steak'],
    ['pork belly', 'food-steak'],
    ['pork', 'food-steak'],
    ['lamb', 'food-steak'],
    ['veal', 'food-steak'],
    ['bison', 'food-steak'],
    ['venison', 'food-steak'],
    ['bacon', 'food-steak'],
    ['ham', 'food-steak'],
    ['prosciutto', 'food-steak'],
    ['pancetta', 'food-steak'],
    ['salami', 'food-steak'],
    ['pepperoni', 'food-steak'],
    ['sausage', 'sausage'],
    ['bratwurst', 'sausage'],
    ['chorizo', 'sausage'],
    ['kielbasa', 'sausage'],
    ['hot dog', 'sausage'],
    ['frank', 'sausage'],
    ['deli meat', 'food-steak'],
    ['lunch meat', 'food-steak'],
    ['jerky', 'food-steak'],
    ['salmon', 'fish'],
    ['tuna', 'fish'],
    ['cod', 'fish'],
    ['halibut', 'fish'],
    ['tilapia', 'fish'],
    ['trout', 'fish'],
    ['mahi', 'fish'],
    ['swordfish', 'fish'],
    ['catfish', 'fish'],
    ['sardine', 'fish'],
    ['anchovy', 'fish'],
    ['bass', 'fish'],
    ['fish', 'fish'],
    ['shrimp', 'fish'],
    ['prawn', 'fish'],
    ['crab', 'fish'],
    ['lobster', 'fish'],
    ['scallop', 'fish'],
    ['clam', 'fish'],
    ['mussel', 'fish'],
    ['oyster', 'fish'],
    ['calamari', 'fish'],
    ['squid', 'fish'],
    ['octopus', 'fish'],
    ['seafood', 'fish'],

    // ── Bakery ──
    ['sourdough', 'bread-slice'],
    ['whole wheat', 'bread-slice'],
    ['multigrain', 'bread-slice'],
    ['rye bread', 'bread-slice'],
    ['white bread', 'bread-slice'],
    ['bread', 'bread-slice'],
    ['baguette', 'baguette'],
    ['ciabatta', 'baguette'],
    ['focaccia', 'baguette'],
    ['french bread', 'baguette'],
    ['italian bread', 'baguette'],
    ['roll', 'bread-slice'],
    ['bun', 'bread-slice'],
    ['brioche', 'bread-slice'],
    ['naan', 'bread-slice'],
    ['pita', 'bread-slice'],
    ['flatbread', 'bread-slice'],
    ['tortilla', 'bread-slice'],
    ['wrap', 'bread-slice'],
    ['bagel', 'circle-double'],
    ['english muffin', 'circle-double'],
    ['croissant', 'croissant'],
    ['pastry', 'croissant'],
    ['danish', 'croissant'],
    ['muffin', 'muffin'],
    ['scone', 'muffin'],
    ['biscuit', 'muffin'],
    ['cornbread', 'muffin'],
    ['donut', 'circle-double'],
    ['doughnut', 'circle-double'],
    ['cake', 'cake-variant'],
    ['cupcake', 'cupcake'],
    ['brownie', 'cake-variant'],
    ['pie', 'pie'],
    ['tart', 'pie'],
    ['cookie', 'cookie'],
    ['waffle', 'waffle'],
    ['pancake', 'circle-double'],
    ['cracker', 'cookie'],

    // ── Frozen ──
    ['frozen pizza', 'pizza'],
    ['frozen vegetable', 'snowflake'],
    ['frozen fruit', 'snowflake'],
    ['frozen meal', 'snowflake'],
    ['frozen dinner', 'snowflake'],
    ['frozen waffle', 'waffle'],
    ['frozen burrito', 'burrito'],
    ['ice', 'ice-cream'],
    ['frozen', 'snowflake'],

    // ── Pantry: Grains & Pasta ──
    ['spaghetti', 'noodles'],
    ['linguine', 'noodles'],
    ['fettuccine', 'noodles'],
    ['penne', 'noodles'],
    ['rigatoni', 'noodles'],
    ['macaroni', 'noodles'],
    ['mac and cheese', 'noodles'],
    ['ramen', 'noodles'],
    ['udon', 'noodles'],
    ['soba', 'noodles'],
    ['lo mein', 'noodles'],
    ['pad thai', 'noodles'],
    ['noodle', 'noodles'],
    ['pasta', 'noodles'],
    ['lasagna', 'noodles'],
    ['white rice', 'rice'],
    ['brown rice', 'rice'],
    ['jasmine rice', 'rice'],
    ['basmati', 'rice'],
    ['sushi rice', 'rice'],
    ['wild rice', 'rice'],
    ['rice', 'rice'],
    ['quinoa', 'barley'],
    ['couscous', 'barley'],
    ['farro', 'barley'],
    ['bulgur', 'barley'],
    ['barley', 'barley'],
    ['oat', 'barley'],
    ['oatmeal', 'barley'],
    ['granola', 'barley'],
    ['muesli', 'barley'],
    ['cereal', 'bowl-mix'],

    // ── Pantry: Canned & Jarred ──
    ['canned tomato', 'can'],
    ['tomato sauce', 'can'],
    ['tomato paste', 'can'],
    ['marinara', 'can'],
    ['pasta sauce', 'can'],
    ['salsa', 'can'],
    ['canned bean', 'can'],
    ['canned tuna', 'can'],
    ['canned chicken', 'can'],
    ['canned soup', 'can'],
    ['canned corn', 'can'],
    ['canned', 'can'],
    ['soup', 'bowl-mix-outline'],
    ['broth', 'bowl-mix-outline'],
    ['stock', 'bowl-mix-outline'],
    ['bouillon', 'bowl-mix-outline'],

    // ── Pantry: Oils, Vinegars, Condiments ──
    ['olive oil', 'bottle-tonic'],
    ['coconut oil', 'bottle-tonic'],
    ['vegetable oil', 'bottle-tonic'],
    ['canola oil', 'bottle-tonic'],
    ['sesame oil', 'bottle-tonic'],
    ['avocado oil', 'bottle-tonic'],
    ['oil', 'bottle-tonic'],
    ['vinegar', 'bottle-tonic'],
    ['balsamic', 'bottle-tonic'],
    ['soy sauce', 'bottle-soda-classic'],
    ['fish sauce', 'bottle-soda-classic'],
    ['hot sauce', 'bottle-soda-classic'],
    ['sriracha', 'bottle-soda-classic'],
    ['tabasco', 'bottle-soda-classic'],
    ['worcestershire', 'bottle-soda-classic'],
    ['teriyaki', 'bottle-soda-classic'],
    ['bbq sauce', 'bottle-soda-classic'],
    ['ketchup', 'bottle-soda-classic'],
    ['mustard', 'bottle-soda-classic'],
    ['mayo', 'bottle-soda-classic'],
    ['mayonnaise', 'bottle-soda-classic'],
    ['ranch', 'bottle-soda-classic'],
    ['dressing', 'bottle-soda-classic'],
    ['sauce', 'bottle-soda-classic'],
    ['relish', 'bottle-soda-classic'],
    ['hummus', 'bowl-mix'],
    ['guacamole', 'bowl-mix'],
    ['dip', 'bowl-mix'],

    // ── Pantry: Baking ──
    ['flour', 'grain'],
    ['sugar', 'cube-outline'],
    ['brown sugar', 'cube-outline'],
    ['powdered sugar', 'cube-outline'],
    ['baking soda', 'shaker-outline'],
    ['baking powder', 'shaker-outline'],
    ['yeast', 'shaker-outline'],
    ['vanilla', 'bottle-tonic-outline'],
    ['extract', 'bottle-tonic-outline'],
    ['cocoa', 'shaker-outline'],
    ['chocolate chip', 'cookie'],
    ['sprinkles', 'shaker-outline'],
    ['frosting', 'cake-variant'],
    ['corn starch', 'shaker-outline'],
    ['cornstarch', 'shaker-outline'],
    ['gelatin', 'shaker-outline'],

    // ── Pantry: Spreads & Nuts ──
    ['peanut butter', 'jar-outline'],
    ['almond butter', 'jar-outline'],
    ['cashew butter', 'jar-outline'],
    ['nutella', 'jar-outline'],
    ['jam', 'jar-outline'],
    ['jelly', 'jar-outline'],
    ['preserves', 'jar-outline'],
    ['marmalade', 'jar-outline'],
    ['honey', 'bee'],
    ['maple syrup', 'bottle-tonic-outline'],
    ['syrup', 'bottle-tonic-outline'],
    ['molasses', 'bottle-tonic-outline'],
    ['peanut', 'peanut'],
    ['almond', 'peanut'],
    ['cashew', 'peanut'],
    ['walnut', 'peanut'],
    ['pecan', 'peanut'],
    ['pistachio', 'peanut'],
    ['macadamia', 'peanut'],
    ['hazelnut', 'peanut'],
    ['pine nut', 'peanut'],
    ['nut', 'peanut'],
    ['seed', 'seed'],
    ['sunflower', 'seed'],
    ['pumpkin seed', 'seed'],
    ['chia', 'seed'],
    ['flax', 'seed'],
    ['hemp seed', 'seed'],
    ['sesame', 'seed'],

    // ── Pantry: Beans & Legumes ──
    ['black bean', 'seed-outline'],
    ['kidney bean', 'seed-outline'],
    ['pinto bean', 'seed-outline'],
    ['navy bean', 'seed-outline'],
    ['chickpea', 'seed-outline'],
    ['garbanzo', 'seed-outline'],
    ['lentil', 'seed-outline'],
    ['split pea', 'seed-outline'],
    ['bean', 'seed-outline'],

    // ── Pantry: Spices & Seasonings ──
    ['salt', 'shaker'],
    ['pepper', 'shaker'],
    ['black pepper', 'shaker'],
    ['cinnamon', 'shaker-outline'],
    ['cumin', 'shaker-outline'],
    ['paprika', 'shaker-outline'],
    ['turmeric', 'shaker-outline'],
    ['cayenne', 'shaker-outline'],
    ['chili powder', 'shaker-outline'],
    ['garlic powder', 'shaker-outline'],
    ['onion powder', 'shaker-outline'],
    ['nutmeg', 'shaker-outline'],
    ['ginger powder', 'shaker-outline'],
    ['curry', 'shaker-outline'],
    ['bay leaf', 'leaf'],
    ['spice', 'shaker-outline'],
    ['seasoning', 'shaker-outline'],
    ['herb', 'leaf'],

    // ── Beverages ──
    ['coffee bean', 'coffee'],
    ['espresso', 'coffee'],
    ['coffee', 'coffee'],
    ['green tea', 'tea'],
    ['black tea', 'tea'],
    ['herbal tea', 'tea'],
    ['chamomile', 'tea'],
    ['tea', 'tea'],
    ['orange juice', 'cup-water'],
    ['apple juice', 'cup-water'],
    ['cranberry juice', 'cup-water'],
    ['grape juice', 'cup-water'],
    ['juice', 'cup-water'],
    ['lemonade', 'cup-water'],
    ['smoothie', 'blender'],
    ['protein shake', 'shaker'],
    ['soda', 'bottle-soda'],
    ['cola', 'bottle-soda'],
    ['sprite', 'bottle-soda'],
    ['ginger ale', 'bottle-soda'],
    ['tonic', 'bottle-soda'],
    ['sparkling water', 'bottle-soda'],
    ['seltzer', 'bottle-soda'],
    ['la croix', 'bottle-soda'],
    ['sparkling', 'bottle-soda'],
    ['kombucha', 'bottle-soda'],
    ['energy drink', 'lightning-bolt'],
    ['red bull', 'lightning-bolt'],
    ['monster', 'lightning-bolt'],
    ['sports drink', 'bottle-soda-classic-outline'],
    ['gatorade', 'bottle-soda-classic-outline'],
    ['coconut water', 'cup-water'],
    ['water', 'water'],
    ['wine', 'glass-wine'],
    ['champagne', 'glass-wine'],
    ['prosecco', 'glass-wine'],
    ['red wine', 'glass-wine'],
    ['white wine', 'glass-wine'],
    ['rosé', 'glass-wine'],
    ['rose wine', 'glass-wine'],
    ['beer', 'beer'],
    ['ipa', 'beer'],
    ['lager', 'beer'],
    ['stout', 'beer'],
    ['ale', 'beer'],
    ['hard seltzer', 'beer'],
    ['cider', 'beer'],
    ['sake', 'glass-wine'],
    ['whiskey', 'glass-tulip'],
    ['bourbon', 'glass-tulip'],
    ['scotch', 'glass-tulip'],
    ['vodka', 'glass-tulip'],
    ['gin', 'glass-tulip'],
    ['rum', 'glass-tulip'],
    ['tequila', 'glass-tulip'],
    ['brandy', 'glass-tulip'],
    ['liquor', 'glass-tulip'],
    ['liqueur', 'glass-tulip'],
    ['cocktail', 'glass-cocktail'],
    ['margarita', 'glass-cocktail'],

    // ── Snacks ──
    ['chip', 'food-croissant'],
    ['tortilla chip', 'food-croissant'],
    ['potato chip', 'food-croissant'],
    ['pretzel', 'pretzel'],
    ['popcorn', 'popcorn'],
    ['trail mix', 'peanut'],
    ['mixed nut', 'peanut'],
    ['granola bar', 'food-croissant'],
    ['protein bar', 'food-croissant'],
    ['energy bar', 'food-croissant'],
    ['candy', 'candy'],
    ['candy bar', 'candy'],
    ['gummy', 'candy'],
    ['gummi', 'candy'],
    ['licorice', 'candy'],
    ['chocolate', 'candy-outline'],
    ['dark chocolate', 'candy-outline'],
    ['white chocolate', 'candy-outline'],
    ['dried fruit', 'fruit-cherries'],
    ['raisin', 'fruit-cherries'],
    ['crouton', 'bread-slice-outline'],
    ['rice cake', 'circle-outline'],
    ['fruit snack', 'fruit-cherries'],

    // ── Prepared & Convenience ──
    ['pizza', 'pizza'],
    ['burrito', 'burrito'],
    ['taco', 'taco'],
    ['wrap', 'burrito'],
    ['sandwich', 'food-hot-dog'],
    ['sub', 'food-hot-dog'],
    ['hot dog', 'food-hot-dog'],
    ['hamburger', 'hamburger'],
    ['burger', 'hamburger'],
    ['sushi', 'rice'],
    ['dumpling', 'food-drumstick'],
    ['pot pie', 'pie'],
    ['empanada', 'pie'],
    ['samosa', 'pie'],

    // ── Breakfast ──
    ['pancake mix', 'circle-double'],
    ['waffle mix', 'waffle'],
    ['french toast', 'bread-slice'],
    ['breakfast', 'egg-fried'],
    ['syrup', 'bottle-tonic-outline'],

    // ── Household ──
    ['paper towel', 'paper-roll'],
    ['toilet paper', 'paper-roll'],
    ['tissue', 'paper-roll'],
    ['napkin', 'paper-roll'],
    ['paper plate', 'paper-roll'],
    ['trash bag', 'trash-can-outline'],
    ['garbage bag', 'trash-can-outline'],
    ['recycling', 'recycle'],
    ['aluminum foil', 'rectangle-outline'],
    ['foil', 'rectangle-outline'],
    ['plastic wrap', 'rectangle-outline'],
    ['cling wrap', 'rectangle-outline'],
    ['parchment paper', 'rectangle-outline'],
    ['wax paper', 'rectangle-outline'],
    ['ziploc', 'package-variant-closed'],
    ['storage bag', 'package-variant-closed'],
    ['freezer bag', 'package-variant-closed'],
    ['container', 'package-variant-closed'],
    ['dish soap', 'water-outline'],
    ['hand soap', 'hand-wash'],
    ['laundry detergent', 'washing-machine'],
    ['detergent', 'washing-machine'],
    ['fabric softener', 'washing-machine'],
    ['dryer sheet', 'washing-machine'],
    ['bleach', 'bottle-tonic-skull-outline'],
    ['cleaning spray', 'spray'],
    ['disinfectant', 'spray'],
    ['all purpose cleaner', 'spray'],
    ['glass cleaner', 'spray'],
    ['windex', 'spray'],
    ['lysol', 'spray'],
    ['cleaning', 'spray'],
    ['cleaner', 'spray'],
    ['wipe', 'spray'],
    ['sponge', 'sponge'],
    ['scrub brush', 'sponge'],
    ['steel wool', 'sponge'],
    ['mop', 'broom'],
    ['broom', 'broom'],
    ['dustpan', 'broom'],
    ['vacuum', 'vacuum'],
    ['vacuum bag', 'vacuum'],
    ['light bulb', 'lightbulb-outline'],
    ['bulb', 'lightbulb-outline'],
    ['battery', 'battery'],
    ['batteries', 'battery'],
    ['candle', 'candle'],
    ['match', 'fire'],
    ['lighter', 'fire'],
    ['air freshener', 'air-filter'],
    ['febreze', 'air-filter'],
    ['bug spray', 'bug-outline'],
    ['insect', 'bug-outline'],
    ['ant trap', 'bug-outline'],
    ['pet food', 'dog'],
    ['dog food', 'dog'],
    ['cat food', 'cat'],
    ['cat litter', 'cat'],

    // ── Personal Care ──
    ['shampoo', 'bottle-tonic-plus-outline'],
    ['conditioner', 'bottle-tonic-plus-outline'],
    ['body wash', 'shower-head'],
    ['shower gel', 'shower-head'],
    ['bar soap', 'hand-wash-outline'],
    ['soap', 'hand-wash-outline'],
    ['face wash', 'face-man-shimmer-outline'],
    ['cleanser', 'face-man-shimmer-outline'],
    ['moisturizer', 'face-man-shimmer-outline'],
    ['lotion', 'lotion-plus-outline'],
    ['body lotion', 'lotion-plus-outline'],
    ['hand cream', 'lotion-plus-outline'],
    ['sunscreen', 'white-balance-sunny'],
    ['spf', 'white-balance-sunny'],
    ['deodorant', 'human'],
    ['antiperspirant', 'human'],
    ['toothpaste', 'toothbrush'],
    ['toothbrush', 'toothbrush'],
    ['mouthwash', 'cup-water'],
    ['floss', 'toothbrush'],
    ['dental', 'tooth-outline'],
    ['razor', 'razor-double-edge'],
    ['shaving cream', 'razor-double-edge'],
    ['shaving', 'razor-double-edge'],
    ['hair gel', 'hair-dryer-outline'],
    ['hair spray', 'hair-dryer-outline'],
    ['hair', 'hair-dryer-outline'],
    ['comb', 'hair-dryer-outline'],
    ['brush', 'hair-dryer-outline'],
    ['cotton ball', 'circle-small'],
    ['cotton pad', 'circle-small'],
    ['cotton swab', 'circle-small'],
    ['q-tip', 'circle-small'],
    ['cotton', 'circle-small'],
    ['band-aid', 'bandage'],
    ['bandage', 'bandage'],
    ['first aid', 'medical-bag'],
    ['medicine', 'pill'],
    ['medication', 'pill'],
    ['ibuprofen', 'pill'],
    ['tylenol', 'pill'],
    ['aspirin', 'pill'],
    ['advil', 'pill'],
    ['allergy', 'pill'],
    ['cold medicine', 'pill'],
    ['cough', 'pill'],
    ['pill', 'pill'],
    ['vitamin', 'pill'],
    ['supplement', 'pill'],
    ['probiotic', 'pill'],
    ['protein powder', 'shaker'],
    ['collagen', 'pill'],
    ['makeup', 'palette-swatch'],
    ['mascara', 'palette-swatch'],
    ['lipstick', 'palette-swatch'],
    ['foundation', 'palette-swatch'],
    ['eyeliner', 'palette-swatch'],
    ['nail polish', 'palette-swatch'],
    ['cosmetic', 'palette-swatch'],
    ['perfume', 'spray-bottle'],
    ['cologne', 'spray-bottle'],
    ['fragrance', 'spray-bottle'],
    ['contact lens', 'eye-outline'],
    ['contact solution', 'eye-outline'],
    ['tampon', 'package-variant'],
    ['pad', 'package-variant'],
    ['diaper', 'baby-bottle-outline'],
    ['baby wipe', 'baby-bottle-outline'],
    ['baby food', 'baby-bottle-outline'],
    ['formula', 'baby-bottle-outline'],
    ['baby', 'baby-bottle-outline'],
];

// ---------------------------------------------------------------------------
// Lookup helpers
// ---------------------------------------------------------------------------

/**
 * Returns the best MaterialCommunityIcons name for a grocery item.
 * Checks item name against keyword map, falls back to category icon.
 */
export function getIconForItem(name: string, category: GroceryCategory): GroceryIconName {
    const lower = name.toLowerCase();

    for (const [keyword, icon] of ICON_MAP) {
        if (lower.includes(keyword)) {
            return icon;
        }
    }

    return CATEGORY_ICONS[category];
}

/**
 * Returns the category-level icon.
 */
export function getCategoryIcon(category: GroceryCategory): GroceryIconName {
    return CATEGORY_ICONS[category];
}
