/**
 * Packing Icon System
 *
 * Maps packing item names to MaterialCommunityIcons via @expo/vector-icons.
 * Uses keyword matching with category fallbacks.
 */
import type { PackingCategory } from '@/types/travel';

export type PackingIconName = string;

// Category-level fallback icons
export const CATEGORY_ICONS: Record<PackingCategory, PackingIconName> = {
    clothes: 'tshirt-crew',
    toiletries: 'water-outline',
    electronics: 'laptop',
    documents: 'file-document-outline',
    medications: 'pill',
    accessories: 'watch',
    misc: 'package-variant',
};

// Keyword → icon mapping (more specific keywords first)
const ICON_MAP: [string, PackingIconName][] = [
    // ── Clothes ──
    ['t-shirt', 'tshirt-crew'],
    ['tshirt', 'tshirt-crew'],
    ['shirt', 'tshirt-crew'],
    ['dress shirt', 'tshirt-crew'],
    ['blouse', 'tshirt-crew'],
    ['polo', 'tshirt-crew'],
    ['tank top', 'tshirt-crew'],
    ['pants', 'human-male'],
    ['jeans', 'human-male'],
    ['trousers', 'human-male'],
    ['shorts', 'human-male'],
    ['skirt', 'human-female'],
    ['dress', 'human-female'],
    ['underwear', 'human'],
    ['boxers', 'human'],
    ['briefs', 'human'],
    ['bra', 'human'],
    ['socks', 'shoe-sneaker'],
    ['sock', 'shoe-sneaker'],
    ['pajamas', 'bed'],
    ['pjs', 'bed'],
    ['sleepwear', 'bed'],
    ['nightgown', 'bed'],
    ['robe', 'bed'],
    ['jacket', 'jacket-outline'],
    ['coat', 'jacket-outline'],
    ['hoodie', 'jacket-outline'],
    ['windbreaker', 'jacket-outline'],
    ['raincoat', 'jacket-outline'],
    ['parka', 'jacket-outline'],
    ['vest', 'jacket-outline'],
    ['sweater', 'tshirt-crew-outline'],
    ['cardigan', 'tshirt-crew-outline'],
    ['pullover', 'tshirt-crew-outline'],
    ['sweatshirt', 'tshirt-crew-outline'],
    ['fleece', 'tshirt-crew-outline'],
    ['swimsuit', 'swim'],
    ['swimwear', 'swim'],
    ['bikini', 'swim'],
    ['trunks', 'swim'],
    ['wetsuit', 'swim'],
    ['sneakers', 'shoe-sneaker'],
    ['running shoes', 'shoe-sneaker'],
    ['shoes', 'shoe-formal'],
    ['boots', 'shoe-heel'],
    ['sandals', 'shoe-cleat'],
    ['flip flops', 'shoe-cleat'],
    ['slippers', 'shoe-cleat'],
    ['heels', 'shoe-heel'],
    ['loafers', 'shoe-formal'],
    ['belt', 'circle-outline'],
    ['tie', 'tie'],
    ['necktie', 'tie'],
    ['bow tie', 'tie'],
    ['scarf', 'scarf'],
    ['gloves', 'hand-back-right-outline'],
    ['mittens', 'hand-back-right-outline'],
    ['hat', 'hat-fedora'],
    ['cap', 'hat-fedora'],
    ['beanie', 'hat-fedora'],
    ['sunhat', 'hat-fedora'],

    // ── Toiletries ──
    ['toothbrush', 'toothbrush'],
    ['toothpaste', 'toothbrush'],
    ['floss', 'tooth-outline'],
    ['mouthwash', 'cup-water'],
    ['deodorant', 'human'],
    ['shampoo', 'bottle-tonic-plus-outline'],
    ['conditioner', 'bottle-tonic-plus-outline'],
    ['body wash', 'shower-head'],
    ['soap', 'hand-wash-outline'],
    ['face wash', 'face-man-shimmer-outline'],
    ['cleanser', 'face-man-shimmer-outline'],
    ['moisturizer', 'lotion-plus-outline'],
    ['lotion', 'lotion-plus-outline'],
    ['lip balm', 'lipstick'],
    ['chapstick', 'lipstick'],
    ['razor', 'razor-double-edge'],
    ['shaving', 'razor-double-edge'],
    ['sunscreen', 'white-balance-sunny'],
    ['spf', 'white-balance-sunny'],
    ['makeup', 'palette-swatch'],
    ['cosmetic', 'palette-swatch'],
    ['perfume', 'spray-bottle'],
    ['cologne', 'spray-bottle'],
    ['hair dryer', 'hair-dryer'],
    ['blow dryer', 'hair-dryer'],
    ['straightener', 'hair-dryer'],
    ['curling iron', 'hair-dryer'],
    ['hair', 'hair-dryer-outline'],
    ['comb', 'hair-dryer-outline'],
    ['brush', 'hair-dryer-outline'],
    ['contact lens', 'eye-outline'],
    ['contact solution', 'eye-outline'],
    ['cotton', 'circle-small'],
    ['q-tip', 'circle-small'],
    ['nail clipper', 'content-cut'],
    ['tweezers', 'content-cut'],
    ['tissue', 'paper-roll'],

    // ── Electronics ──
    ['phone charger', 'cellphone-charging'],
    ['phone', 'cellphone'],
    ['iphone', 'cellphone'],
    ['laptop charger', 'power-plug-outline'],
    ['charger', 'power-plug-outline'],
    ['laptop', 'laptop'],
    ['macbook', 'laptop'],
    ['computer', 'laptop'],
    ['tablet', 'tablet'],
    ['ipad', 'tablet'],
    ['headphones', 'headphones'],
    ['earbuds', 'headphones'],
    ['airpods', 'headphones'],
    ['earphones', 'headphones'],
    ['power bank', 'battery-charging'],
    ['portable charger', 'battery-charging'],
    ['battery pack', 'battery-charging'],
    ['camera', 'camera'],
    ['gopro', 'camera'],
    ['tripod', 'camera-outline'],
    ['drone', 'quadcopter'],
    ['travel adapter', 'power-plug-outline'],
    ['adapter', 'power-plug-outline'],
    ['converter', 'power-plug-outline'],
    ['usb cable', 'usb'],
    ['usb', 'usb'],
    ['lightning cable', 'usb'],
    ['cable', 'usb'],
    ['cord', 'usb'],
    ['kindle', 'book-open-variant'],
    ['e-reader', 'book-open-variant'],
    ['reader', 'book-open-variant'],
    ['speaker', 'speaker'],
    ['bluetooth', 'bluetooth'],
    ['watch charger', 'watch'],
    ['smart watch', 'watch'],
    ['sd card', 'sd'],
    ['memory card', 'sd'],
    ['hard drive', 'harddisk'],
    ['flash drive', 'usb-flash-drive'],
    ['extension cord', 'power-plug-outline'],

    // ── Documents ──
    ['passport', 'passport'],
    ['visa', 'card-account-details-outline'],
    ['id', 'card-account-details-outline'],
    ['license', 'card-account-details-outline'],
    ['driver', 'card-account-details-outline'],
    ['boarding pass', 'airplane-takeoff'],
    ['ticket', 'ticket-outline'],
    ['travel insurance', 'shield-check-outline'],
    ['insurance', 'shield-check-outline'],
    ['hotel confirmation', 'office-building-outline'],
    ['reservation', 'office-building-outline'],
    ['itinerary', 'clipboard-text-outline'],
    ['credit card', 'credit-card-outline'],
    ['debit card', 'credit-card-outline'],
    ['card', 'credit-card-outline'],
    ['cash', 'cash'],
    ['money', 'cash'],
    ['currency', 'cash'],
    ['map', 'map-outline'],
    ['guide', 'book-outline'],
    ['address', 'map-marker-outline'],
    ['emergency contact', 'phone-alert-outline'],
    ['vaccination', 'needle'],
    ['vaccine', 'needle'],
    ['covid', 'needle'],

    // ── Medications ──
    ['prescription', 'pill'],
    ['medication', 'pill'],
    ['medicine', 'pill'],
    ['pill', 'pill'],
    ['pain reliever', 'pill'],
    ['ibuprofen', 'pill'],
    ['tylenol', 'pill'],
    ['aspirin', 'pill'],
    ['advil', 'pill'],
    ['allergy medicine', 'pill'],
    ['antihistamine', 'pill'],
    ['vitamin', 'pill'],
    ['supplement', 'pill'],
    ['inhaler', 'lungs'],
    ['epipen', 'needle'],
    ['insulin', 'needle'],
    ['band-aid', 'bandage'],
    ['bandage', 'bandage'],
    ['first aid', 'medical-bag'],
    ['thermometer', 'thermometer'],
    ['eye drops', 'eye-outline'],
    ['motion sickness', 'pill'],
    ['melatonin', 'weather-night'],
    ['sleep aid', 'weather-night'],
    ['antacid', 'pill'],

    // ── Accessories ──
    ['sunglasses', 'sunglasses'],
    ['glasses', 'glasses'],
    ['reading glasses', 'glasses'],
    ['watch', 'watch'],
    ['jewelry', 'diamond-stone'],
    ['necklace', 'diamond-stone'],
    ['bracelet', 'diamond-stone'],
    ['ring', 'diamond-stone'],
    ['earring', 'diamond-stone'],
    ['wallet', 'wallet'],
    ['purse', 'bag-personal-outline'],
    ['handbag', 'bag-personal-outline'],
    ['backpack', 'bag-personal'],
    ['day bag', 'bag-personal'],
    ['day pack', 'bag-personal'],
    ['fanny pack', 'bag-personal-outline'],
    ['tote', 'bag-personal-outline'],
    ['duffel', 'bag-suitcase'],
    ['suitcase', 'bag-suitcase'],
    ['carry-on', 'bag-suitcase'],
    ['luggage', 'bag-suitcase'],
    ['umbrella', 'umbrella-outline'],
    ['rain', 'umbrella-outline'],
    ['travel pillow', 'pillow'],
    ['neck pillow', 'pillow'],
    ['pillow', 'pillow'],
    ['eye mask', 'sleep'],
    ['sleep mask', 'sleep'],
    ['blanket', 'bed-outline'],
    ['water bottle', 'bottle-wine-outline'],
    ['bottle', 'bottle-wine-outline'],
    ['thermos', 'bottle-wine-outline'],
    ['luggage lock', 'lock-outline'],
    ['lock', 'lock-outline'],
    ['padlock', 'lock-outline'],
    ['luggage tag', 'tag-outline'],
    ['tag', 'tag-outline'],
    ['key', 'key-outline'],
    ['carabiner', 'hook'],

    // ── Misc ──
    ['snack', 'food-apple-outline'],
    ['food', 'food-apple-outline'],
    ['granola bar', 'food-croissant'],
    ['protein bar', 'food-croissant'],
    ['book', 'book-open-variant'],
    ['novel', 'book-open-variant'],
    ['magazine', 'book-open-variant'],
    ['journal', 'notebook-outline'],
    ['notebook', 'notebook-outline'],
    ['pen', 'pen'],
    ['pencil', 'pencil'],
    ['laundry bag', 'washing-machine'],
    ['laundry', 'washing-machine'],
    ['dry bag', 'package-variant-closed'],
    ['zip-lock', 'package-variant-closed'],
    ['ziploc', 'package-variant-closed'],
    ['plastic bag', 'package-variant-closed'],
    ['packing cube', 'cube-outline'],
    ['packing', 'cube-outline'],
    ['compression bag', 'cube-outline'],
    ['sewing kit', 'needle'],
    ['safety pin', 'pin-outline'],
    ['duct tape', 'tape-measure'],
    ['tape', 'tape-measure'],
    ['towel', 'paper-roll'],
    ['beach towel', 'paper-roll'],
    ['game', 'gamepad-variant-outline'],
    ['cards', 'cards-playing-outline'],
    ['playing cards', 'cards-playing-outline'],
    ['binoculars', 'binoculars'],
    ['flashlight', 'flashlight'],
    ['torch', 'flashlight'],
    ['multi-tool', 'wrench-outline'],
    ['knife', 'knife'],
    ['swiss army', 'wrench-outline'],
    ['insect repellent', 'bug-outline'],
    ['bug spray', 'bug-outline'],
    ['mosquito', 'bug-outline'],
];

/**
 * Returns the best MaterialCommunityIcons name for a packing item.
 * Checks item name against keyword map, falls back to category icon.
 */
export function getPackingIcon(name: string, category: PackingCategory): PackingIconName | null {
    const lower = name.toLowerCase();

    for (const [keyword, icon] of ICON_MAP) {
        if (lower.includes(keyword)) {
            return icon;
        }
    }

    return null;
}

/**
 * Returns the category-level icon.
 */
export function getPackingCategoryIcon(category: PackingCategory): PackingIconName {
    return CATEGORY_ICONS[category];
}
